### ISSUE TITLE
Open VSX Registry: Awareness and Important Steps

### ISSUE THREAD

**Issue by brianking** [bmalehorn/vscode-fish#17]
@mauricioklein has published this extension in the [Open VSX Registry](https://open-vsx.org/extension/bmalehorn/vscode-fish).

The service was recently transferred to the Eclipse Foundation and we want to ensure a seamless transition for our users. To ensure uninterrupted service and more exposure for your extension, I recommend the following.

**To the maintainers**: If you would like to take over publishing to open-vsx.org, here’s how: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

**To the current publisher**: Please sign the [Eclipse Publisher Agreement](https://www.eclipse.org/legal/documents/eclipse-openvsx-publisher-agreement.pdf). The signing process is [explained in the Wiki](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) (steps 1 and 2).

**Claiming ownership of the namespace for your extension(s)**. To find out how to do this, see:
https://github.com/eclipse/openvsx/wiki/Namespace-Access
As owner you can add more namespace members (including service accounts) yourself in https://open-vsx.org/user-settings/namespaces. Note that publishing can be done by any contributor to the extension, namely those you add as namespace members once they have signed the Publisher Agreement as well.

Please also note that a license is now mandatory for publishing your extension to Open VSX. If your project doesn't have any license, please add one, preferably an [open source license](https://opensource.org/licenses) such as MIT. The publishing tool [ovsx](https://www.npmjs.com/package/ovsx) offers to automatically add the MIT license when you try to publish without a license.

Useful links:
[Eclipse Publisher Agreement](https://www.eclipse.org/legal/documents/eclipse-openvsx-publisher-agreement.pdf)
[Eclipse Foundation Open VSX Registry Frequently Asked Questions (FAQ)](https://www.eclipse.org/legal/open-vsx-registry-faq/) 

More details are in these recent blog posts:
https://blogs.eclipse.org/post/brian-king/open-vsx-registry-under-new-management
https://blogs.eclipse.org/post/brian-king/new-era-open-vsx-registry

Today, there’s growing momentum around open source tools and technologies that support Visual Studio (VS) Code extensions. Leading global organizations are adopting these tools and technologies. This momentum has spurred demand for a marketplace without restrictions and limitations. We hope you join us on this journey as we continue to build the Open VSX community. 
We look forward to continued innovation from you in 2021!

**Comment by bmalehorn** [comment]
@mauricioklein It's not clear to me from the message - do I need to do anything?

I'm fine with my extensions being published to places like Open VSX as long as:

1. it takes no ongoing work for me to publish (I can keep publishing only to the to regular VSX registry)
2. I have the option of taking over publishing in the future

Do you need anything from me in the meantime?

**Comment by mauricioklein** [comment]
Hello!

I'm not sure about my participation here either 😂

Looks like the extension was already claimed by the owner, so it isn't under my username anymore.

Please let me know if you need any action from my side to complete the transfer.

Thanks!

**Comment by bmalehorn** [comment]
@brianking Why did you make this ticket? What do you need from me?

**Comment by brianking** [comment]
The latest version is now published by open-vsx: https://open-vsx.org/extension/bmalehorn/vscode-fish/1.0.20.

So @mauricioklein for you to do currently.

@bmalehorn I would recommend you at least take ownership of the namespace. I don't think taking over publishing would be too much of an overhead; I'd say the additional effort is very low because the ovsx publishing tool works very similarly to Microsoft’s vsce.

**Comment by bmalehorn** [comment]
Eh, I'd rather not. Publishing is already the most painful part of maintaining these extensions, since each publication requires logging into some website and generating a very specific token (since the last token has expired). Now I'd have to do that twice. I'd rather only publish to one repository to keep things as easy as possible for my future self to update this extension so I don't just give up.

I want to avoid committing to going through Open VSX just to remove a banner from a website for a text editor I don't use. People are free to use this extension for whatever, but I'm going to prioritize my long-term happiness over reaching every user.

**Comment by brianking** [comment]
Understood, thanks for considering.
