### ISSUE TITLE
Extra newline on paste

### ISSUE THREAD

**Issue by PatrickF1** [bmalehorn/vscode-fish#21]
Whenever I paste into VSCode with this extension enabled, a newline is inserted right after whenever I pasted.

For example, say I have this text
```
echo "hi"<CURSOR>
```
if I copy "something" and hit paste, my buffer becomes
```
echo "hi"something
<CUROSOR>
```
Version: 1.0.22
Resolution steps tried
- uninstalling and re-installing
- disabling and re-enabling
- checked my paste key binding and nothing is suspicious about it

**Comment by bmalehorn** [comment]
@PatrickF1 This doesn't happen for me:

![Screen Recording 2021-06-07 at 3 28 12 PM](https://user-images.githubusercontent.com/3344958/121095382-1b827d80-c7a5-11eb-8aaa-e5143485bf37.gif)

If you uninstall vscode-fish and reload, does it still happen?

**Comment by PatrickF1** [comment]
Hi, thanks for getting back to me! Yes, that was one of the resolution steps I tried :(

**Comment by bmalehorn** [comment]
@PatrickF1 Does this only happen in fish files, or does it happen in any other types of files?

And to be clear, when you uninstall vscode-fish and reload, does it still have an extra newline on paste or does it not happen anymore?

**Comment by PatrickF1** [comment]
> Does this only happen in fish files, or does it happen in any other types of files?

Only fish files

> when you uninstall vscode-fish and reload, does it still have an extra newline on paste or does it not happen anymore?

It stops after I uninstall it.

**Comment by PatrickF1** [comment]
I figured this out. It was some bug with Prettier. I uninstalled it and the re-installed it and now this issue is gone. Whew...

**Comment by PatrickF1** [comment]
Actually it came back. FWIW I tried zgm.vscode-fish as well and it had the same bug.
