### ISSUE TITLE
Some small enhancements.

### ISSUE THREAD

**Issue by account-login** [bmalehorn/vscode-fish#22]
Hi. I've made some enhancements in my fork.

Two keys (`indentationRules`, `onEnterRules`) were added to `language-configuration.json` in commit https://github.com/account-login/vscode-fish/commit/0cdd1c8b81e1c0e9dfc8273b72f26738d4e85e01.
The `indentationRules` is for autoindent and the `onEnterRules` is helpful when splitting a comment line into two lines.

I've also made the path of the `fish` command configurable (commit https://github.com/account-login/vscode-fish/commit/fb97292830f569a51870d676f5bae73b9dc49d26) because I'm using `fish` from cygwin and I do not want to expose my cygwin installation to PATH.

What do you think about these?

**Comment by bmalehorn** [comment]
@account-login Great! It didn't occur to me to fix the indentation, and the fish path thing is something I've found useful in other languages but not yet in fish. I've merged both these changes and published a new version of vscode-fish.
