### ISSUE TITLE
(restricted) Workspace Trust support

### ISSUE THREAD

**Issue by dgcampea** [bmalehorn/vscode-fish#24]
Currently vscode-fish is fully disabled when operating in Restricted Mode.
Can "limited" mode be implemented for at least syntax highlighting and extension association to work?

Links (for reference):
- https://code.visualstudio.com/docs/editor/workspace-trust
- https://code.visualstudio.com/api/extension-guides/workspace-trust

**Comment by bmalehorn** [comment]
Sounds simple enough, this might be just a 1-line change.

@dgcampea do you have a good way of reproducing this issue? How can I open a workspace in restricted mode so I can see this issue?

**Comment by dgcampea** [comment]
_Open Folder_ should be enough to trigger a message box that asks for mode selection.

**Comment by bmalehorn** [comment]
@dgcampea I updated it to have limited access, so it now highlights in restricted mode:

before:
![image](https://user-images.githubusercontent.com/3344958/130310434-846694fc-344a-4447-b754-aaa02027879c.png)


after:
![image](https://user-images.githubusercontent.com/3344958/130310431-ff2abfdd-84c9-4ee0-91ba-5c0c323cb5aa.png)

Does it look good from your end?

**Comment by bmalehorn** [comment]
Closing out this issue as resolved.
