### ISSUE TITLE
indent behavior of extension is overriding manually specified indent within vscode

### ISSUE THREAD

**Issue by syd3n** [bmalehorn/vscode-fish#3]
When I have the `vscode-fish` extension disabled, and specify `Indent Using Tabs` with a specific `Tab Size` set, the indentation I have specified while editing a `*.fish` file will stick and there are no issues.

But if I have the `vscode_fish` extension enabled, and open a `*.fish` file for editing and then specific `Indent Using Tabs` and specific a `Tab Size`, the auto format will go back to spaces. I am not able to figure out how to change this behavior. Any suggestions?

Attaching a vid of what I am describing. Please let me know if what I am describing is not clear.

[fish-ext-indent-issue.mp4.zip](https://github.com/bmalehorn/vscode-fish/files/4233554/fish-ext-indent-issue.mp4.zip)

**Comment by bmalehorn** [comment]
@syd3n Thanks for the bug report! Sorry I didn't see this earlier.

`vscode-fish` uses the fish shell's builtin `fish_indent` command. This command is hard-coded to indent to 4 spaces [here](https://github.com/fish-shell/fish-shell/blob/3cf1de1b7f5849882f154de7019ff0860e98cdde/src/fish_indent.cpp#L50), so unfortunately there's no way for the extension to pass `Ident Using Tabs` preference to `fish_indent`.

As a workaround, you can disable format on save for fish files:

1. Ctrl+Shift+P / Cmd+Shift+P
2. Type `Preference: Open Keyboard Shortcuts (JSON)`
3. Add this code:
```json
  "[fish]": {
    "editor.formatOnSave": false,
  },
```

**Comment by MariuzM** [comment]
Just double checking, there is no way to indent this to 2 spaces / tabs? :( eh bummer i use 2 tabs for all my projects

**Comment by weisi** [comment]
According to the maintainer of fish-shell, the number of spaces per indent isn't supposed to be configurable (think `gofmt` which defines a "standard" formatting for a language). Previous discussion at https://github.com/fish-shell/fish-shell/pull/6790

**Comment by bmalehorn** [comment]
Yup, 4 spaces is just the way it is. Closing this issue out.
