### ISSUE TITLE
Error: spawn fish ENOENT

### ISSUE THREAD

**Issue by ghost** [bmalehorn/vscode-fish#33]
I'm on Silverblue using the integrated terminal as a toolbox created with `flatpak-spawn` and I'm seeing the `Error: spawn fish ENOENT` every time I open a fish script. Any way to make it work together? Thanks!

**Comment by bmalehorn** [comment]
You need to be able to open a terminal, type `fish`, and have it run successfully. You probably need to `yum install fish` or `apt-get install fish` to make it go away.
