### ISSUE TITLE
Four backslashes break syntax highlighting

### ISSUE THREAD

**Issue by exploide** [bmalehorn/vscode-fish#5]
The following snippet breaks the syntax highlighting since the closing single-quote is erroneously treated as being escaped.

```fish
set backslash '\\\\'
set foo "broken highlighting"
```

![fish-backslash](https://user-images.githubusercontent.com/5670236/78691184-a4c7c700-78f8-11ea-9970-f7c0c22210f0.png)

(Apparently this is also true for GitHub's highlighting)

**Comment by bmalehorn** [comment]
Thanks for the report! I've fixed this and pushed out an update.

I'm not super surprised GitHub's syntax highlighting is wrong too. This extension's syntax highlighting was copied from another VSCode extension, which was copied from an Atom extension, which itself was copied from the Sublime extension. It's kind of been passed around forever and rarely scrutinized, I'd bet GitHub's comes from the same buggy lineage.
