### ISSUE TITLE
Not highlighting on shebang trigger

### ISSUE THREAD

**Issue by mcandre** [bmalehorn/vscode-fish#8]
Some of my fish scripts lack the `.fish` extension, but are using a `#!/usr/bin/env fish` shebang. In that case, the vscode-fish plugin fails to highlight the file.

**Comment by exploide** [comment]
This will be fixed in #4 by @benspaulding.

**Comment by bmalehorn** [comment]
I've now merged in #4 - if you update your extension and re-open a file with `#!/usr/bin/env fish`, it should highlight as fish. Closing this out, but feel free to open another issue if you find a case where it's not working.
